server:
  port: 8080

spring:
  application:
    name: quick-docker

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config:classpath:log4j2.xml